name: 'Run action with issue comment'

on:
  issue_comment:
    types:
      - created

jobs:
  run_action_linux:
    if: ${{ github.event.issue.body == 'linux' && github.actor == 'CaiJingLong' }}
    # run with issue number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install @actions/exec
      - uses: actions/github-script@v6
        name: 'Run action'
        with:
          script: |
            const fs = require('fs');
            const issueNumber = context.issue.number;
            const issueComment = context.payload.comment.body;
            const issueCommentFile = `/tmp/issue${issueNumber}.sh`;
            fs.writeFileSync(issueCommentFile, issueComment);
            await exec.exec(`chmod +x ${issueCommentFile}`);
            await exec.exec(issueCommentFile);
            
  run_action_macos:
    if: ${{ github.event.issue.body == 'macos' && github.actor == 'CaiJingLong' }}
    # run with issue number
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install @actions/exec
      - uses: actions/github-script@v6
        name: 'Run action'
        with:
          script: |
            const fs = require('fs');
            const issueNumber = context.issue.number;
            const issueComment = context.payload.comment.body;
            const issueCommentFile = `/tmp/issue${issueNumber}.sh`;
            fs.writeFileSync(issueCommentFile, issueComment);
            await exec.exec(`chmod +x ${issueCommentFile}`);
            await exec.exec(issueCommentFile);

  run_action_windows:
    if: ${{ github.event.issue.body == 'windows' && github.actor == 'CaiJingLong'}}
    # run with issue number
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install @actions/exec
      - uses: actions/github-script@v6
        name: 'Run action'
        with:
          script: |
            const fs = require('fs');
            const issueNumber = context.issue.number;
            const issueComment = context.payload.comment.body;
            const issueCommentFile = `/c/issue${issueNumber}.sh`;
            fs.writeFileSync(issueCommentFile, issueComment);
            await exec.exec(`chmod +x ${issueCommentFile}`);
            await exec.exec(issueCommentFile);
